### ISSUE TITLE
Compatible with Magento 2?

### ISSUE THREAD

**Issue by ErikvdVen** [SanderSander/magento-ideal-checkout#1]
Is this repo compatible with Magento 2, and if not, is it possible to update this repo?

**Comment by SanderSander** [comment]
Hey Erik,

Not sure if it works on magento 2, did not try it. Have to look into it. 
Feel free to make PR, not sure if I have time

**Comment by SanderSander** [comment]
Hey Erik, I didn't know that the difference between 1.9 and 2.0 was so HUGE. everything is rewriting restructured etc. I think is a to big  to make everything compatible with 2.0. 

I'm not sure if ideal-checkout comes with an updated version, let's hope so.
